name: 'Action to create puppet module repository from template'
description: 'create puppet module repository from template'
inputs:
  pr_changes:
    require: true
    type: number
    
runs:
  using: "composite"
  steps:
  - id: step1
    shell: bash
    name: create puppet module repository from template
    run: |
      set -eo pipefail
           
      changes=${{ inputs.pr_changes }}
      
      echo "Changes to deploy $deploy_changes"
      
      echo "Extracting simlane and release version"
      puppet_repo_name=$(echo $changes | cut -d: -f1)
      team_name=$(echo $changes | cut -d: -f2)
      
      echo "team name is ${team_name}"
   
      echo "Checking the ${puppet_repo_name} repo in workspace already existing or not.."
      gh auth login --with-token < ~/.gh_secrets
      
      repo_list=$(gh repo list | awk '{print $1}' | sed 's/pcherukusfdc\///')
      if [[ $(grep -q ${puppet_repo_name} ${repo_list} 2>/dev/null) == 0 ]]
      then
        echo "Repository ${puppet_repo_name} already exist, quitting..!!"
        gh auth logout --hostname github.com
        exit 0
      else
        echo "Repository ${puppet_repo_name} does not exist, proceding to create.."
      fi
      
      echo "Creating repository ${puppet_repo_name} in workspace "
      gh repo create ${puppet_repo_name} --public
      
      echo $(pwd)
      
      
      echo "Create repo from the template repo"
      if [[ -d 'puppet_module_tpt.git' ]] ; then rm -rf puppet_module_tpt.git ; fi
      
      git clone --bare https://oauth2:$(cat ~/.gh_secrets)@github.com/pcherukusfdc/puppet_module_tpt.git
      
      echo "Changing into puppet template repository"
      cd puppet_module_tpt.git
     
      echo "Cloning the template repository to the new repository.."
      git push --mirror https://oauth2:$(cat ~/.gh_secrets)@github.com/pcherukusfdc/${puppet_repo_name}.git
      
      #echo "Checking if the team exist or not..!!"
      #curl -s -X GET -H "Authorization: Bearer $(cat ~/.gh_secrets)" https://api.github.com/repos/pcherukusfdc/teams | jq -r '.[] | .name' | grep ${team_name}
      #if [[ $? != 0 ]]
      #then
      #  echo "Team does not exist.."
      #else
      #  echo "The team already exist..!!"
      #  echo "Give maintainer access to the team ${team} for repo ${puppet_repo_name}"
        #curl -X PUT -H "Authorization: Bearer $(cat ~/.gh_secrets)" https://api.github.com/repos/pcherukusfdc/${puppet_repo_name}/collaborators/${team} -d '{"permission”:”maintain”}’
        curl -X PUT -H "Authorization: Bearer $(cat ~/.gh_secrets)" https://api.github.com/repos/pcherukusfdc/${puppet_repo_name}/collaborators/prathima-chitturi -d '{"permission”:”maintain”}' >/dev/null
        
        if [[ $? == 0 ]]
        then
          echo "Provided access to the ${team} team to the repository ${puppet_repo_name}"
        else
          echo "Unable to provide access..!!"
          exit 1
        fi
      #fi
